import "./globals.css";

import Header from "@/components/Header";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import RequestButton from "@/components/RequestButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className } flex flex-col items-center justify-start pt-2 gap-3 [&>*]:xl:w-1/3 [&>*]sm:w-10/12 sm:m-8`}
      >
        <Header />
        <RequestButton />
        {children}
      </body>
    </html>
  );
}
